"""Render Phase B CAD documents into safe, local CadQuery scripts."""

from __future__ import annotations

import json

from text_to_cad.agent_schema import (
    AgentCadDocument,
    BooleanOperation,
    CadPart,
    CubePrimitive,
    CylinderPrimitive,
    EdgeOperation,
    HoleOperation,
    Primitive,
    Vec3,
)


def render_agent_cadquery_script(document: AgentCadDocument, output_name: str) -> str:
    """Render a validated CAD document as a self-contained CadQuery script."""

    part = document.parts[0]
    lines = [
        f'"""Generated by Resonance CAD Agent for {output_name}."""',
        "",
        "import os",
        "from pathlib import Path",
        "",
        "OUTPUT_DIR = Path(__file__).resolve().parent",
        'os.environ.setdefault("XDG_CACHE_HOME", str(OUTPUT_DIR / ".cache"))',
        "",
        "import cadquery as cq",
        "",
        f"DOCUMENT = {json.dumps(document.model_dump(mode='json'), indent=2)!r}",
        "",
        _render_part(part),
        "",
        f'cq.exporters.export(part, str(OUTPUT_DIR / "{output_name}.step"))',
        f'cq.exporters.export(part, str(OUTPUT_DIR / "{output_name}.stl"))',
        f'print("Wrote {output_name}.step and {output_name}.stl")',
        "",
    ]
    return "\n".join(lines)


def _render_part(part: CadPart) -> str:
    statements = [_primitive_expression(part.primitive, "part", part.at)]
    for op in part.operations:
        if isinstance(op, HoleOperation):
            statements.append(_hole_statement(op))
        elif isinstance(op, BooleanOperation):
            statements.append(_boolean_statement(op))
        elif isinstance(op, EdgeOperation):
            statements.append(_edge_statement(op))
        else:
            raise TypeError(f"Unsupported operation: {op!r}")
    return "\n".join(statements)


def _primitive_expression(primitive: Primitive, variable: str, at: Vec3) -> str:
    if isinstance(primitive, CubePrimitive):
        expression = (
            f'{variable} = cq.Workplane("XY")'
            f".box({primitive.size.x!r}, {primitive.size.y!r}, {primitive.size.z!r}, centered=(False, False, False))"
        )
    elif isinstance(primitive, CylinderPrimitive):
        expression = (
            f'{variable} = cq.Workplane("XY")'
            f".circle({primitive.radius!r}).extrude({primitive.height!r})"
        )
    else:
        raise TypeError(f"Unsupported primitive: {primitive!r}")

    if at.x or at.y or at.z:
        expression += f".translate(({at.x!r}, {at.y!r}, {at.z!r}))"
    return expression


def _hole_statement(operation: HoleOperation) -> str:
    depth = operation.depth if operation.depth is not None else None
    if depth is None:
        return (
            "part = (part.faces(\">Z\").workplane()"
            f".pushPoints([({operation.at.x!r}, {operation.at.y!r})])"
            f".hole({operation.diameter!r}))"
        )
    return (
        "part = (part.faces(\">Z\").workplane()"
        f".pushPoints([({operation.at.x!r}, {operation.at.y!r})])"
        f".hole({operation.diameter!r}, {depth!r}))"
    )


def _boolean_statement(operation: BooleanOperation) -> str:
    tool_variable = "tool"
    tool_statement = _primitive_expression(operation.primitive, tool_variable, operation.at)
    combine = "union" if operation.type == "union" else "cut"
    return f"{tool_statement}\npart = part.{combine}({tool_variable})"


def _edge_statement(operation: EdgeOperation) -> str:
    method = "fillet" if operation.type == "fillet" else "chamfer"
    return f'part = part.edges("|Z").{method}({operation.radius!r})'
