"""Render Phase B CAD documents into safe, local CadQuery scripts."""

from __future__ import annotations

import json

from text_to_cad.agent_schema import (
    AgentCadDocument,
    BooleanOperation,
    CadPart,
    CubePrimitive,
    CylinderPrimitive,
    EdgeOperation,
    HoleOperation,
    Primitive,
    SpringPrimitive,
    TubePrimitive,
    Vec3,
)


def render_agent_cadquery_script(document: AgentCadDocument, output_name: str) -> str:
    """Render a validated CAD document as a self-contained CadQuery script."""

    part = document.parts[0]
    lines = [
        f'"""Generated by Resonance CAD Agent for {output_name}."""',
        "",
        "import os",
        "from pathlib import Path",
        "",
        "OUTPUT_DIR = Path(__file__).resolve().parent",
        'os.environ.setdefault("XDG_CACHE_HOME", str(OUTPUT_DIR / ".cache"))',
        "",
        "import cadquery as cq",
        "from cadquery import Vector",
        "from math import cos, pi, sin",
        "",
        f"DOCUMENT = {json.dumps(document.model_dump(mode='json'), indent=2)!r}",
        "",
        _helper_functions(),
        "",
        _render_part(part),
        "",
        f'cq.exporters.export(part, str(OUTPUT_DIR / "{output_name}.step"))',
        f'cq.exporters.export(part, str(OUTPUT_DIR / "{output_name}.stl"))',
        f'print("Wrote {output_name}.step and {output_name}.stl")',
        "",
    ]
    return "\n".join(lines)


def _render_part(part: CadPart) -> str:
    statements = [_primitive_expression(part.primitive, "part", part.at)]
    for op in part.operations:
        if isinstance(op, HoleOperation):
            statements.append(_hole_statement(op))
        elif isinstance(op, BooleanOperation):
            statements.append(_boolean_statement(op))
        elif isinstance(op, EdgeOperation):
            statements.append(_edge_statement(op))
        else:
            raise TypeError(f"Unsupported operation: {op!r}")
    return "\n".join(statements)


def _primitive_expression(primitive: Primitive, variable: str, at: Vec3) -> str:
    if isinstance(primitive, CubePrimitive):
        expression = (
            f'{variable} = cq.Workplane("XY")'
            f".box({primitive.size.x!r}, {primitive.size.y!r}, {primitive.size.z!r}, centered=(False, False, False))"
        )
    elif isinstance(primitive, CylinderPrimitive):
        expression = (
            f'{variable} = cq.Workplane("XY")'
            f".circle({primitive.radius!r}).extrude({primitive.height!r})"
        )
    elif isinstance(primitive, SpringPrimitive):
        expression = (
            f"{variable} = make_helical_spring("
            f"coil_radius={primitive.coil_radius!r}, "
            f"wire_radius={primitive.wire_radius!r}, "
            f"height={primitive.height!r}, "
            f"turns={primitive.turns!r}, "
            f"samples_per_turn={primitive.samples_per_turn!r})"
        )
    elif isinstance(primitive, TubePrimitive):
        expression = (
            f"{variable} = make_bushing("
            f"outer_radius={primitive.outer_radius!r}, "
            f"inner_radius={primitive.inner_radius!r}, "
            f"height={primitive.height!r}, "
            f"chamfer={primitive.chamfer!r})"
        )
    else:
        raise TypeError(f"Unsupported primitive: {primitive!r}")

    if at.x or at.y or at.z:
        expression += f".translate(({at.x!r}, {at.y!r}, {at.z!r}))"
    return expression


def _helper_functions() -> str:
    return '''def make_helical_spring(coil_radius, wire_radius, height, turns, samples_per_turn):
    sample_count = max(24, int(turns * samples_per_turn))
    points = []
    for index in range(sample_count + 1):
        t = index / sample_count
        angle = 2.0 * pi * turns * t
        points.append(Vector(coil_radius * cos(angle), coil_radius * sin(angle), height * t))
    path = cq.Workplane("XY").spline(points)
    profile = cq.Workplane("YZ").center(coil_radius, 0).circle(wire_radius)
    return profile.sweep(path, isFrenet=True)


def make_bushing(outer_radius, inner_radius, height, chamfer):
    result = (
        cq.Workplane("XZ")
        .moveTo(inner_radius, 0)
        .lineTo(outer_radius, 0)
        .lineTo(outer_radius, height)
        .lineTo(inner_radius, height)
        .close()
        .revolve(360)
    )
    if chamfer and chamfer > 0:
        try:
            result = result.faces(">Z").edges("%Circle").chamfer(chamfer)
            result = result.faces("<Z").edges("%Circle").chamfer(chamfer)
        except Exception:
            pass
    return result
'''


def _hole_statement(operation: HoleOperation) -> str:
    depth = operation.depth if operation.depth is not None else None
    if depth is None:
        return (
            "part = (part.faces(\">Z\").workplane()"
            f".pushPoints([({operation.at.x!r}, {operation.at.y!r})])"
            f".hole({operation.diameter!r}))"
        )
    return (
        "part = (part.faces(\">Z\").workplane()"
        f".pushPoints([({operation.at.x!r}, {operation.at.y!r})])"
        f".hole({operation.diameter!r}, {depth!r}))"
    )


def _boolean_statement(operation: BooleanOperation) -> str:
    tool_variable = "tool"
    tool_statement = _primitive_expression(operation.primitive, tool_variable, operation.at)
    combine = "union" if operation.type == "union" else "cut"
    return f"{tool_statement}\npart = part.{combine}({tool_variable})"


def _edge_statement(operation: EdgeOperation) -> str:
    method = "fillet" if operation.type == "fillet" else "chamfer"
    return f'part = part.edges("|Z").{method}({operation.radius!r})'
